language: dart
dart:
  - stable
with_content_shell: true
before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3
script:
  - pub publish --dry-run # Validate package
  - pub run dart_dev gen-test-runner --check
  - pub run dart_dev format --check
  - pub run dart_dev analyze
  #- pub run dart_dev coverage --no-html
  - pub run dart_dev test # Remove once coverage works with Dart latest
  - bash <(curl -s https://codecov.io/bash) -f coverage/coverage.lcov
