language: dart
dart:
  - stable
script:
  - pub run dart_dev gen-test-runner --check
  - pub run dart_dev format --check
  - pub run dart_dev analyze
  #- pub run dart_dev coverage --no-html
  - pub run dart_dev test # Remove once coverage works with Dart latest
  - bash <(curl -s https://codecov.io/bash) -f coverage/coverage.lcov
