language: dart
sudo: required
addons:
  chrome: stable

dart:
  - 1.24.3
  - stable

script:
  - pub publish --dry-run
  - pub run dart_dev format --check
  - pub run dart_dev analyze
  - pub run dart_dev test

