language: dart
sudo: required
addons:
  chrome: stable

dart:
  - 1.24.3
  - 2.0.0

script:
  - dartfmt -n --set-exit-if-changed example lib test tool
  - dartanalyzer lib test/unit
  - pub publish --dry-run
  - xvfb-run --server-args="-screen 0 1024x768x24" tool/test.sh
