language: dart
sudo: required
addons:
  chrome: stable

dart:
  - 1.24.3
  - stable

script:
  - tool/format.sh
  - dartanalyzer lib bin test/unit
  - pub publish --dry-run
  - xvfb-run --server-args="-screen 0 1024x768x24" tool/test.sh
