language: dart
sudo: required

dart:
  - 1.24.3
  - dev
dart_task:
  - dartfmt: true
  - dartanalyzer: lib example tool test/unit

script:
  - pub publish --dry-run # Validate package
  - pub run dart_dev gen-test-runner --check
  - tool/test.sh
  #- pub run dart_dev coverage --no-html
  - bash <(curl -s https://codecov.io/bash) -f coverage/coverage.lcov
