name: w_common
version: 1.20.1
description: General utilities for Dart projects.
author: Workiva Client Platform Team <team-clientplatform@workiva.com>
homepage: https://www.github.com/Workiva/w_common

environment:
  sdk: '>=2.4.0 <3.0.0'

dependencies:
  args: ^1.5.1
  async: ">=1.13.3 <3.0.0"
  colorize: ">=0.1.2 <3.0.0"
  glob: ^1.1.7
  intl: ">=0.14.0 <0.16.0"
  js: ^0.6.1+1
  logging: ^0.11.0
  meta: ^1.0.4
  package_config: ^1.0.3
  package_resolver: ^1.0.2
  path: ^1.5.1
  sass: ^1.6.0
  source_maps: ^0.10.5
  watcher: ^0.9.6

dev_dependencies:
  build_runner: ^1.7.1
  build_test: ^0.10.9
  build_web_compilers: ^2.5.1
  dependency_validator: ^1.4.0
  mockito: ^4.1.1
  test: ^1.9.1
