name: w_common
description: General utilities for Dart projects.
version: 1.2.0
author: Workiva Client Platform Team <team-clientplatform@workiva.com>
homepage: https://www.github.com/Workiva/w_common

environment:
  sdk: '>=1.21.0 <2.0.0'

dependencies:
  meta: ^1.0.4

dev_dependencies:
  analyzer: ^0.29.0
  coverage: ^0.7.2
  dart_dev: ^1.5.0
  dart_style: ^0.2.4
  dartdoc: ^0.9.0
  test: ^0.12.4
