name: w_common
version: 1.13.0
description: General utilities for Dart projects.
author: Workiva Client Platform Team <team-clientplatform@workiva.com>
homepage: https://www.github.com/Workiva/w_common

environment:
  sdk: '>=1.12.0 <3.0.0'

web:
  compiler:
    debug: dartdevc

dependencies:
  dart2_constant: ^1.0.0
  intl: ">=0.14.0 <0.16.0"
  logging: ^0.11.0
  meta: ^1.0.4

dev_dependencies:
  build_runner: ">=0.6.0 <1.0.0"
  build_test: ">=0.9.0 <1.0.0"
  build_web_compilers: ">=0.2.0 <1.0.0"
  dart_dev: ^1.9.5
  mockito: ">=0.8.0"
  test: ^0.12.30

transformers:
  - test/pub_serve:
      $include: test/**_test{s*.*,}dart
